server:
  port: 8071

spring:
  application:
    name: sp-goods
  main:
    allow-bean-definition-overriding: true
  ##########################################################
  #
  #           数据源配置
  #
  ##########################################################
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://api.ckhun.co/sharing_platform?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ckkhh
    password: Chen778520
    hikari:
      connection-timeout: 100000
  ##########################################################
  #
  #           nacos配置
  #
  ##########################################################
  cloud:
    nacos:
      discovery:
        server-addr: 120.24.108.55:8848
        username: ckkhh
        password: Chen778520
  ##########################################################
  #
  #           Redis配置
  #
  ##########################################################
  redis:
    host: api.ckhun.co
    password: Chen778520
    spring:
      redis:
        jedis:
          pool: max-active=20
    timeout: 30000
############################################################
#
# mybatis mapper 配置
#
############################################################
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
      update-strategy: not_empty
feign:
  client:
    config:
      default:
        connectTimeout: 10000  #单位毫秒
        readTimeout: 10000