
##################################################################
#
#                   nacos配置
#
##################################################################
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.24.108.55:8848

