server:
  port: 8086

spring:
  application:
    name: sp-marketing

  cloud:
    nacos:
      discovery:
        server-addr: 120.24.108.55:8848
        username: ckkhh
        password: Chen778520

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://api.ckhun.co:3306/sharing_platform?characterEncoding=utf-8
    username: ckkhh
    password: Chen778520
    hikari:
      connection-timeout: 30000
      read-only: false
      maximum-pool-size: 60
      minimum-idle: 10

mybatis-plus:
  mapper-locations: classpath:/com.ckhun/*/mapper/*Mapper.xml
  type-aliases-package: com.ckhun.pojo.entity
  global-config:
    db-config:
      id-type: auto

  configuration:
    cache-enabled: false