server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.24.108.55:8848
        username: ckkhh
        password: Chen778520


    gateway:
      discovery:
        locator:
          enabled: true

      routes:
#
#        - id: orders-router
#          uri: lb://sp-orders
#          predicates:
#            - Path=/sp-orders/**
#          filters:
#            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
  application:
    name: sp-gateway